########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.modules.client.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: client-config
  labels:
    fateMoudle: client
{{ include "fate.labels" . | indent 4 }}
data:
  server_conf.json: |
    {
        "servers": {
            "proxy": {
                "host": "{{ .Values.modules.rollsite.ip }}", 
                "port": 9370
            }, 
            "fateboard": {
                "host": "{{ .Values.modules.python.fateboardIp }}", 
                "port": 8080
            }, 
            "fateflow": {
                "host": "{{ .Values.modules.python.fateflowIp }}", 
                "grpc.port": 9360,
                "http.port": 9380
            }, 
            {{ if .Values.modules.serving }}
            "servings": [
                "{{ .Values.modules.serving.ip }}:{{ .Values.modules.serving.port }}"
            ],
            {{ end }}
            "fml_agent": {
                "host": "{{ .Values.modules.python.fateflowIp }}", 
                "port": 8484
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    fateMoudle: client
{{ include "fate.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: client
{{ include "fate.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        fateMoudle: client
{{ include "fate.labels" . | indent 8 }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "client"
      containers:
        - image: {{ .Values.image.registry }}/client:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: client
          env:
            - name: partyId
              value: {{ .Values.partyId | quote  }}
          ports:
            - containerPort: 20000
          volumeMounts:
            - mountPath: /data/projects/fate/python/arch/conf/server_conf.json
              name: client-confs
              subPath: server_conf.json
            - mountPath: /data/projects/fate/python/fate_flow/settings.py
              subPath: settings.py
              name: python-confs
            - name: logs
              mountPath: /data/projects/fate/client/logs
      {{- with .Values.modules.client.nodeSelector }}
      nodeSelector: 
      {{- range $k, $v := . }}
        {{ $k }}: {{ $v }}
      {{- end }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: client-confs
          configMap:
            name: client-config
        - name: python-confs
          configMap:
            name: python-config
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    fateMoudle: client
{{ include "fate.labels" . | indent 4 }}
spec:
  ports:
    - name: "20000"
      port: 20000
      targetPort: 20000
      protocol: TCP
  type: {{ .Values.modules.client.type }}
  selector:
    fateMoudle: client
{{ include "fate.matchLabels" . | indent 4 }}
---
{{ end }}