########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.modules.client.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: client-config
  labels:
    fateMoudle: fateflow
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
data:
  server_conf.json: |
    {
        "servers": {
            "proxy": {
                "host": "{{ .Values.modules.proxy.ip }}", 
                "port": 9370
            }, 
            "fateboard": {
                "host": "{{ .Values.modules.fateboard.ip }}", 
                "port": 8080
            }, 
            "roll": {
                "host": "{{ .Values.modules.roll.ip }}", 
                "port": 8011
            }, 
            "fateflow": {
                "host": "{{ .Values.modules.fateflow.ip }}", 
                "grpc.port": 9360,
                "http.port": 9380
            }, 
            "federation": {
                "host": "{{ .Values.modules.federation.ip }}", 
                "port": 9394
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    fateMoudle: client
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: client
      name: {{ .Values.partyName  | quote }}
      partyId: {{ .Values.partyId | quote  }}
  template:
    metadata:
      labels:
        fateMoudle: client
        name: {{ .Values.partyName | quote  }}
        partyId: {{ .Values.partyId | quote  }}
        owner: kubefate
        cluster: fate
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "client"
      containers:
        - image: {{ .Values.image.registry }}/client:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: client
          ports:
            - containerPort: 20000
          volumeMounts:
            - mountPath: /data/projects/fate/python/arch/conf/server_conf.json
              name: client-confs
              subPath: server_conf.json
            - name: logs
              mountPath: /data/projects/fate/client/logs
      {{ if .Values.nodeSelector.client.value}}
      nodeSelector:
        {{ .Values.nodeSelector.python.nodeLabel }}: {{ .Values.nodeSelector.python.value }}
      {{ end }}
      restartPolicy: Always
      volumes:
        - name: client-confs
          configMap:
            name: client-config
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    fateMoudle: client
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
spec:
  ports:
    - name: "20000"
      port: 20000
      targetPort: 20000
      protocol: TCP
  type: {{ .Values.modules.fateboard.type }}
  selector:
    fateMoudle: client
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
---
{{ end }}