########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.modules.federation.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: federation-config
  labels:
    fateMoudle: federation
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
data:
  federation.properties: |
    party.id={{ .Values.partyId }}
    service.port=9394
    meta.service.ip={{ .Values.modules.metaService.ip }}
    meta.service.port=8590
    proxy.ip={{ .Values.modules.proxy.ip }}
    proxy.port=9370
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: federation
  labels:
    fateMoudle: federation
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: federation
      name: {{ .Values.partyName | quote  }}
      partyId: {{ .Values.partyId | quote  }}
  template:
    metadata:
      labels:
        fateMoudle: federation
        name: {{ .Values.partyName | quote  }}
        partyId: {{ .Values.partyId | quote  }}
        owner: kubefate
        cluster: fate
    spec:
      containers:
        - image: {{ .Values.image.registry }}/federation:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: federation
          ports:
            - containerPort: 9394
          volumeMounts:
            - mountPath: /data/projects/fate/federation/conf/federation.properties
              name: federation-confs
              subPath: federation.properties
      {{ if .Values.nodeSelector.federation.value}}
      nodeSelector:
        {{ .Values.nodeSelector.federation.nodeLabel }}: {{ .Values.nodeSelector.federation.value }}
      {{ end }}
      restartPolicy: Always
      volumes:
        - name: federation-confs
          configMap:
            name: federation-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    fateMoudle: federation
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
  name: federation
spec:
  ports:
    - name: "9394"
      port: 9394
      targetPort: 9394
      protocol: TCP
  type: {{ .Values.modules.federation.type }}
  selector:
    fateMoudle: federation
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
---
{{ end }}