########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.modules.metaService.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: meta-service-config
  labels:
    fateMoudle: meta-service
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
data:
  meta-service.properties: |
    party.id={{ .Values.partyId }}
    service.port=8590
    
    jdbc.driver.classname=com.mysql.cj.jdbc.Driver
    jdbc.url=jdbc:mysql://{{ .Values.modules.mysql.ip }}:3306/{{ .Values.mysql.mysql_database | default "fate" }}?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    jdbc.username={{ .Values.mysql.mysql_user | default "fate" }}
    jdbc.password={{ .Values.mysql.mysql_password | default "fate_dev" }}
    target.project=meta-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-service
  labels:
    fateMoudle: meta-service
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: meta-service
      name: {{ .Values.partyName | quote  }}
      partyId: {{ .Values.partyId | quote  }}
  template:
    metadata:
      labels:
        fateMoudle: meta-service
        name: {{ .Values.partyName | quote  }}
        partyId: {{ .Values.partyId | quote  }}
        owner: kubefate
        cluster: fate
    spec:
      containers:
        - image: {{ .Values.image.registry }}/meta-service:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: meta-service
          ports:
            - containerPort: 8590
          volumeMounts:
            - mountPath: /data/projects/fate/meta-service/conf/meta-service.properties
              name: meta-service-confs
              subPath: meta-service.properties
      {{ if .Values.nodeSelector.metaService.value}}
      nodeSelector:
        {{ .Values.nodeSelector.metaService.nodeLabel }}: {{ .Values.nodeSelector.metaService.value }}
      {{ end }}
      restartPolicy: Always
      volumes:
        - name: meta-service-confs
          configMap:
            name: meta-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: meta-service
  labels:
    fateMoudle: meta-service
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
spec:
  ports:
    - name: "8590"
      port: 8590
      targetPort: 8590
      protocol: TCP
  type: {{ .Values.modules.metaService.type }}
  selector:
    fateMoudle: meta-service
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
---
{{ end }}