########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.modules.proxy.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-config
  labels:
    fateMoudle: proxy
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote }}
    owner: kubefate
    cluster: fate
data:
  proxy.properties: |
    coordinator={{ .Values.partyId }}
    ip=0.0.0.0
    port=9370
    route.table=/data/projects/fate/proxy/conf/route_table.json
    #server.crt=/Users/max-webank/Projects/fdn/fdn-proxy/src/main/resources/certs/server.crt
    #server.key=/Users/max-webank/Projects/fdn/fdn-proxy/src/main/resources/certs/server-private.pem
    root.crt=
  route_table.json: |
    {
        "route_table": {
            "default": {
                "default": [
                    {
                      {{- with .Values.exchange -}}
                        "ip": "{{ .partyIp }}",
                        "port": {{ .partyPort }}
                      {{- else -}}
                        "ip": "proxy",
                        "port": 9370
                      {{- end -}}
                    }
                ]
            },
            {{- range .Values.partyList }}
            "{{ .partyId }}": {
                "default": [
                    {
                        "ip": "{{ .partyIp }}",
                        "port": "{{ .partyPort }}"
                    }
                ]
            },
            {{- end }}
            "{{ .Values.partyId }}": {
                "fate": [
                    {
                        "ip": "{{ .Values.modules.federation.ip }}",
                        "port": 9394
                    }
                ],
                "fateflow": [
                    {
                        "ip": "{{ .Values.modules.fateflow.ip }}",
                        "port": 9360
                    }
                ]
            }
        },
        "permission": {
            "default_allow": true
        }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    fateMoudle: proxy
    name: {{ .Values.partyName  | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: proxy
      name: {{ .Values.partyName  | quote }}
      partyId: {{ .Values.partyId | quote  }}
  template:
    metadata:
      labels:
        fateMoudle: proxy
        name: {{ .Values.partyName | quote  }}
        partyId: {{ .Values.partyId | quote  }}
        owner: kubefate
        cluster: fate
    spec:
      containers:
        - image: {{ .Values.image.registry }}/proxy:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: proxy
          ports:
            - containerPort: 9370
          volumeMounts:
            - mountPath: /data/projects/fate/proxy/conf/proxy.properties
              name: proxy-confs
              subPath: proxy.properties
            - mountPath: /data/projects/fate/proxy/conf/route_table.json
              name: proxy-confs
              subPath: route_table.json
      {{ if .Values.nodeSelector.proxy.value}}
      nodeSelector:
        {{ .Values.nodeSelector.proxy.nodeLabel }}: {{ .Values.nodeSelector.proxy.value }}
      {{ end }}
      restartPolicy: Always
      volumes:
        - name: proxy-confs
          configMap:
            name: proxy-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    fateMoudle: proxy
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote }}
    owner: kubefate
    cluster: fate
  name: proxy
spec:
  ports:
    - name: "9370"
      port: 9370
      nodePort: {{ .Values.nodePort }}
      targetPort: 9370
      protocol: TCP
  type: {{ .Values.modules.proxy.type }}
  selector:
    fateMoudle: proxy
    name: {{ .Values.partyName }}
    partyId: {{ .Values.partyId | quote  }}
---
{{ end }}