########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.modules.roll.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: roll-config
  labels:
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
data:
  roll.properties: |
    party.id={{ .Values.partyId }}
    service.port=8011
    meta.service.ip={{ .Values.modules.metaService.ip }}
    meta.service.port=8590
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roll
  labels:
    fateMoudle: roll
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: roll
      name: {{ .Values.partyName | quote  }}
      partyId: {{ .Values.partyId | quote  }}
  template:
    metadata:
      labels:
        fateMoudle: roll
        name: {{ .Values.partyName | quote  }}
        partyId: {{ .Values.partyId | quote  }}
        owner: kubefate
        cluster: fate
    spec:
      containers:
        - image: {{ .Values.image.registry }}/roll:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: roll
          ports:
            - containerPort: 8011
          volumeMounts:
            - mountPath: /data/projects/fate/roll/conf/roll.properties
              name: roll-confs
              subPath: roll.properties
      {{ if .Values.nodeSelector.roll.value}}
      nodeSelector:
        {{ .Values.nodeSelector.roll.nodeLabel }}: {{ .Values.nodeSelector.roll.value }}
      {{ end }}
      volumes:
        - name: roll-confs
          configMap:
            name: roll-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    fateMoudle: roll
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
  name: roll
spec:
  ports:
    - name: "8011"
      port: 8011
      targetPort: 8011
      protocol: TCP
  type: {{ .Values.modules.roll.type }}
  selector:
    fateMoudle: roll
    name: {{ .Values.partyName  | quote }}
    partyId: {{ .Values.partyId | quote  }}
---
{{ end }}
