#nfspath: /data/fate-data
#nfsserver: 192.168.0.2

image:
  registry: {{ .registry | default "federatedai" }}
  isThridParty:
  tag: 1.3.0-release
  pullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
partyId: {{ .partyId }}
partyName: {{ .name }}
host:
  fateboard: {{ .partyId }}.fateboard.kubefate.net
  client: {{ .partyId }}.notebook.kubefate.net
nodePort: {{ with .proxy }}{{ .nodePort }}{{ end }}

exchange:
{{- with .proxy }}
{{- with .exchange }}
  partyIp: {{ .ip }}
  partyPort: {{ .port }}
{{- end }}
{{- end }}
partyList:
{{- with .proxy }}
{{- range .partyList }}
  - partyId: {{ .partyId }}
    partyIp: {{ .partyIp }}
    partyPort: {{ .partyPort }}
{{- end }}
{{- end }}
mysql:
  mysql_root_password: {{.externalMysqlRootPassword|default "fate_dev"}}
  mysql_database: {{.externalMysqlDatabase|default "fate"}}
  mysql_user: {{.externalMysqlUser|default "fate"}}
  mysql_password: {{.externalMysqlPassword|default "fate_dev"}}
redis:
  requirepass: {{.externalRedisPassword|default "fate_dev"}}
eggList:
{{- with .egg }}
{{- range .count | int | until }}
  - egg: egg{{ . }}
    nodeLabel: fedai.org
    value:
{{- end }}
{{- end }}
nodeSelector:
  fateboard:
    nodeLabel: fedai.org
    value: 
  federation:
    nodeLabel: fedai.org
    value: 
  metaService:
    nodeLabel: fedai.org
    value: 
  mysql:
    nodeLabel: fedai.org
    value: 
  proxy:
    nodeLabel: fedai.org
    value: 
  python:
    nodeLabel: fedai.org
    value: 
  redis:
    nodeLabel: fedai.org
    value: 
  roll:
    nodeLabel: fedai.org
    value: 
  servingServer:
    nodeLabel: fedai.org
    value: 
modules: 
  proxy: 
    include: {{ has "proxy" .modules }}
    ip: proxy
    type: {{ .proxy.type | default "ClusterIP" }}
  egg: 
    include: {{ has "egg" .modules }}
    processorSessionMaxCount: {{ .egg.processor }}
    ip: egg
    type: ClusterIP
  fateboard: 
    include: {{ has "fateboard" .modules }}
    ip: fateboard
    type: ClusterIP
  fateflow: 
    include: {{ has "fateflow" .modules }}
    ip: fateflow
    type: ClusterIP
  federation: 
    include: {{ has "federation" .modules }}
    ip: federation
    type: ClusterIP
  metaService: 
    include: {{ has "metaService" .modules }}
    ip: meta-service
    type: ClusterIP
  mysql: 
    include: {{ has "mysql" .modules }}
    ip: {{.externalMysqlIp|default "mysql"}}
    type: ClusterIP
  redis: 
    include: {{ has "redis" .modules }}
    ip: {{.externalRedisIp|default "redis"}}
    type: ClusterIP
  roll: 
    include: {{ has "roll" .modules }}
    ip: roll
    type: ClusterIP
  python: 
    include: {{ has "python" .modules }}
    ip: python
    type: ClusterIP
  client: 
    include: {{ has "client" .modules }}
    ip: client
    type: ClusterIP
  serving: 
    include: true
    ip: {{ .servingIp }}
    port: {{ .servingPort }}
    type: ClusterIP
    